name = "print-app-backend"
main = "server.js"
compatibility_date = "2026-03-11"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "https://buildergrids.tech"
ADMIN_FRONTEND_URL = "https://admin.buildergrids.tech"
ALLOWED_ORIGINS = "https://buildergrids.tech"

[observability]
enabled = true

[observability.logs]
enabled = true

[observability.traces]
enabled = true

[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "print-jobs"
